// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App handles application lifecycle and settings window management.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetOS returns the current operating system identifier (darwin, windows, or linux).
 * Used by the frontend to read/write OS-specific paths in OSPathMap.
 * @returns {$CancellablePromise<string>}
 */
export function GetOS() {
    return $Call.ByID(816844233);
}

/**
 * PickDirectory opens a native directory picker dialog and returns the selected path.
 * Returns an empty string if the user cancels the dialog.
 * @param {string} currentPath
 * @returns {$CancellablePromise<string>}
 */
export function PickDirectory(currentPath) {
    return $Call.ByID(1347829059, currentPath);
}

/**
 * ShowSettingsWindow opens the settings window, creating it if needed.
 * @returns {$CancellablePromise<void>}
 */
export function ShowSettingsWindow() {
    return $Call.ByID(2596981913);
}
