// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandService handles all command and category CRUD operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateCategory creates a new Category with the given name, icon, color and returns the created Category or an error.
 * @param {string} name
 * @param {string} icon
 * @param {string} color
 * @returns {$CancellablePromise<$models.Category>}
 */
export function CreateCategory(name, icon, color) {
    return $Call.ByID(3920645540, name, icon, color).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateCommand creates a new Command with the given fields and returns the created Command or an error.
 * @param {string} title
 * @param {string} description
 * @param {string} scriptBody
 * @param {string} categoryID
 * @param {string[]} tags
 * @param {$models.VariableDefinition[]} variables
 * @param {$models.OSPathMap} workingDir
 * @returns {$CancellablePromise<$models.Command>}
 */
export function CreateCommand(title, description, scriptBody, categoryID, tags, variables, workingDir) {
    return $Call.ByID(3040387109, title, description, scriptBody, categoryID, tags, variables, workingDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteCategory deletes the category with the given id.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCategory(id) {
    return $Call.ByID(2228038743, id);
}

/**
 * DeleteCommand deletes the command with the given id.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCommand(id) {
    return $Call.ByID(1888656992, id);
}

/**
 * DeletePreset deletes the VariablePreset with the given presetID after validating it belongs to commandID.
 * @param {string} commandID
 * @param {string} presetID
 * @returns {$CancellablePromise<void>}
 */
export function DeletePreset(commandID, presetID) {
    return $Call.ByID(1347137556, commandID, presetID);
}

/**
 * GetCategories returns all categories from the DB.
 * @returns {$CancellablePromise<$models.Category[]>}
 */
export function GetCategories() {
    return $Call.ByID(1124386808).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetCommands returns all commands from the DB.
 * @returns {$CancellablePromise<$models.Command[]>}
 */
export function GetCommands() {
    return $Call.ByID(2230805162).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetCommandsByCategory returns all commands belonging to the given categoryID.
 * @param {string} categoryID
 * @returns {$CancellablePromise<$models.Command[]>}
 */
export function GetCommandsByCategory(categoryID) {
    return $Call.ByID(3544855671, categoryID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetPresets returns all variable presets for the given commandID.
 * @param {string} commandID
 * @returns {$CancellablePromise<$models.VariablePreset[]>}
 */
export function GetPresets(commandID) {
    return $Call.ByID(2933858456, commandID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetScriptBody returns just the body (for simple mode editing)
 * @param {string} commandID
 * @returns {$CancellablePromise<string>}
 */
export function GetScriptBody(commandID) {
    return $Call.ByID(707578151, commandID);
}

/**
 * GetScriptContent returns the full script content for the editor
 * @param {string} commandID
 * @returns {$CancellablePromise<string>}
 */
export function GetScriptContent(commandID) {
    return $Call.ByID(1214515992, commandID);
}

/**
 * RenameCommand sets a new title for the command with the given id and returns the updated Command.
 * @param {string} id
 * @param {string} newTitle
 * @returns {$CancellablePromise<$models.Command>}
 */
export function RenameCommand(id, newTitle) {
    return $Call.ByID(3511040027, id, newTitle).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ReorderCommand moves a command to a new position within a category (or to a
 * different category). newCategoryId may be empty string for uncategorized.
 * newPosition is the 0-based index within the target category.
 * @param {string} id
 * @param {number} newPosition
 * @param {string} newCategoryId
 * @returns {$CancellablePromise<$models.Command[]>}
 */
export function ReorderCommand(id, newPosition, newCategoryId) {
    return $Call.ByID(2371488912, id, newPosition, newCategoryId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ReorderPresets reorders the presets for commandID to match the given presetIDs slice.
 * @param {string} commandID
 * @param {string[]} presetIDs
 * @returns {$CancellablePromise<void>}
 */
export function ReorderPresets(commandID, presetIDs) {
    return $Call.ByID(4123798965, commandID, presetIDs);
}

/**
 * ResetAllData deletes all data from the database.
 * @returns {$CancellablePromise<void>}
 */
export function ResetAllData() {
    return $Call.ByID(121210722);
}

/**
 * SavePreset creates a new VariablePreset for the given commandID and returns it or an error.
 * @param {string} commandID
 * @param {string} name
 * @param {{ [_ in string]?: string }} values
 * @returns {$CancellablePromise<$models.VariablePreset>}
 */
export function SavePreset(commandID, name, values) {
    return $Call.ByID(2518009278, commandID, name, values).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SearchCommands returns commands matching the given query string.
 * @param {string} query
 * @returns {$CancellablePromise<$models.Command[]>}
 */
export function SearchCommands(query) {
    return $Call.ByID(2165520554, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * UpdateCategory updates a Category's name, icon, and color by id and returns the updated Category or an error.
 * @param {string} id
 * @param {string} name
 * @param {string} icon
 * @param {string} color
 * @returns {$CancellablePromise<$models.Category>}
 */
export function UpdateCategory(id, name, icon, color) {
    return $Call.ByID(871939973, id, name, icon, color).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateCommand updates a Command's fields by id and returns the updated Command or an error.
 * @param {string} id
 * @param {string} title
 * @param {string} description
 * @param {string} scriptBody
 * @param {string} categoryID
 * @param {string[]} tags
 * @param {$models.VariableDefinition[]} variables
 * @param {$models.OSPathMap} workingDir
 * @returns {$CancellablePromise<$models.Command>}
 */
export function UpdateCommand(id, title, description, scriptBody, categoryID, tags, variables, workingDir) {
    return $Call.ByID(2942553414, id, title, description, scriptBody, categoryID, tags, variables, workingDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * UpdatePreset updates an existing VariablePreset by presetID and returns it or an error.
 * @param {string} commandID
 * @param {string} presetID
 * @param {string} name
 * @param {{ [_ in string]?: string }} values
 * @returns {$CancellablePromise<$models.VariablePreset>}
 */
export function UpdatePreset(commandID, presetID, name, values) {
    return $Call.ByID(1219258890, commandID, presetID, name, values).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Category.createFrom;
const $$createType1 = $models.Command.createFrom;
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $Create.Array($$createType1);
const $$createType4 = $models.VariablePreset.createFrom;
const $$createType5 = $Create.Array($$createType4);
