// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ExecutionService handles running commands and execution history.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetVariables returns variable prompts for a command.
 * @param {string} commandID
 * @returns {$CancellablePromise<$models.VariablePrompt[]>}
 */
export function GetVariables(commandID) {
    return $Call.ByID(4101005934, commandID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RunCommand resolves the command's template variables and writes the
 * resulting command line directly to the active terminal session's PTY
 * via TerminalService.Write. Output streams back through the session's
 * pty-output event (handled by Terminal.tsx) and Ctrl+C interrupts are
 * handled by the PTY's foreground process group.
 * @param {string} commandID
 * @param {{ [_ in string]?: string }} variables
 * @returns {$CancellablePromise<$models.ExecutionRecord>}
 */
export function RunCommand(commandID, variables) {
    return $Call.ByID(4143621145, commandID, variables).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RunCommandInSession is RunCommand targeted at an explicit terminal session
 * rather than whichever session is active. The global quick launcher uses it
 * so its output stays self-contained in its dedicated internal session. The
 * ID-addressable behavior is deliberate: internal sessions are a UI
 * visibility/lifecycle convenience, not an access-control boundary.
 * @param {string} commandID
 * @param {{ [_ in string]?: string }} variables
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.ExecutionRecord>}
 */
export function RunCommandInSession(commandID, variables, sessionID) {
    return $Call.ByID(3885689246, commandID, variables, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.VariablePrompt.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ExecutionRecord.createFrom;
