// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportExportService handles importing and exporting commands and theme templates.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExportCommands exports selected commands to a JSON file.
 * @param {string[]} commandIDs
 * @returns {$CancellablePromise<void>}
 */
export function ExportCommands(commandIDs) {
    return $Call.ByID(3360644818, commandIDs);
}

/**
 * ImportCommands imports commands from a JSON file.
 * @returns {$CancellablePromise<$models.Command[]>}
 */
export function ImportCommands() {
    return $Call.ByID(840325137).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SaveThemeTemplate saves a default theme template to a JSON file.
 * @returns {$CancellablePromise<void>}
 */
export function SaveThemeTemplate() {
    return $Call.ByID(1489453142);
}

// Private type creation functions
const $$createType0 = $models.Command.createFrom;
const $$createType1 = $Create.Array($$createType0);
