// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LauncherService owns the global quick launcher: its always-on-top window, the
 * system-wide shortcut that toggles it, and the dedicated terminal session its
 * commands run in. The window and its terminal session are created once and
 * then only shown and hidden, so opening the launcher never rebuilds React
 * state or respawns a shell.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplySettings re-reads the persisted launcher settings and re-registers the
 * global shortcut accordingly. The frontend calls it after changing any
 * launcher setting. It returns the resulting status rather than an error so the
 * UI can show partial success (for example: enabled, but the combination is
 * already taken).
 * @returns {$CancellablePromise<$models.LauncherStatus>}
 */
export function ApplySettings() {
    return $Call.ByID(1845488258).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetSessionID returns the launcher's eagerly-created dedicated terminal
 * session. If eager startup failed, one bounded single-flight recovery attempt
 * is made on demand. A session removed from TerminalService is never returned
 * as a stale ID.
 * @returns {$CancellablePromise<string>}
 */
export function GetSessionID() {
    return $Call.ByID(1892317312);
}

/**
 * GetStatus returns the current launcher/shortcut state.
 * @returns {$CancellablePromise<$models.LauncherStatus>}
 */
export function GetStatus() {
    return $Call.ByID(1596643565).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Hide conceals only the launcher panel without activating or focusing the
 * main Cmdex window, and without destroying the panel or its terminal session.
 * @returns {$CancellablePromise<void>}
 */
export function Hide() {
    return $Call.ByID(2226947441);
}

/**
 * Resize switches the launcher between its compact and expanded heights, used
 * when the inline terminal is revealed or dismissed.
 * @param {boolean} expanded
 * @returns {$CancellablePromise<void>}
 */
export function Resize(expanded) {
    return $Call.ByID(2800369333, expanded);
}

/**
 * SetLaunchAtLogin installs or removes the platform login item and persists the
 * preference.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetLaunchAtLogin(enabled) {
    return $Call.ByID(1624648450, enabled);
}

/**
 * Show reveals and focuses the launcher. On macOS Wails' non-activating panel
 * semantics keep the previously active app active while the native positioning
 * helper selects the display under the pointer. Other platforms use the Wails
 * screen API fallback.
 * @returns {$CancellablePromise<void>}
 */
export function Show() {
    return $Call.ByID(1106717952);
}

/**
 * ShowMainWindow brings the main CmDex window to the front. The launcher offers
 * this so CmDex stays reachable when it was started in background mode.
 * @returns {$CancellablePromise<void>}
 */
export function ShowMainWindow() {
    return $Call.ByID(638969109);
}

/**
 * Toggle shows the launcher when hidden and hides it when visible. This is what
 * the global shortcut invokes.
 * @returns {$CancellablePromise<void>}
 */
export function Toggle() {
    return $Call.ByID(426529913);
}

/**
 * ValidateShortcut reports whether an accelerator string is a usable global
 * shortcut, so the settings UI can reject it before saving.
 * @param {string} accelerator
 * @returns {$CancellablePromise<void>}
 */
export function ValidateShortcut(accelerator) {
    return $Call.ByID(148594645, accelerator);
}

// Private type creation functions
const $$createType0 = $models.LauncherStatus.createFrom;
