// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../database/sql/models.js";

/**
 * AppSettings stores user preferences
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("locale" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["locale"] = "";
        }
        if (!("terminal" in $$source)) {
            /**
             * terminal ID; empty = auto-detect
             * @member
             * @type {string}
             */
            this["terminal"] = "";
        }
        if (!("theme" in $$source)) {
            /**
             * active theme ID
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("lastDarkTheme" in $$source)) {
            /**
             * last used dark theme
             * @member
             * @type {string}
             */
            this["lastDarkTheme"] = "";
        }
        if (!("lastLightTheme" in $$source)) {
            /**
             * last used light theme
             * @member
             * @type {string}
             */
            this["lastLightTheme"] = "";
        }
        if (!("customThemes" in $$source)) {
            /**
             * JSON-encoded []CustomTheme; empty string = "[]"
             * @member
             * @type {string}
             */
            this["customThemes"] = "";
        }
        if (!("uiFont" in $$source)) {
            /**
             * UI sans-serif font
             * @member
             * @type {string}
             */
            this["uiFont"] = "";
        }
        if (!("monoFont" in $$source)) {
            /**
             * monospace font for editor
             * @member
             * @type {string}
             */
            this["monoFont"] = "";
        }
        if (!("density" in $$source)) {
            /**
             * layout density: compact | comfortable | spacious
             * @member
             * @type {string}
             */
            this["density"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * nil = leave unchanged; non-nil empty map = clear.
             * @member
             * @type {OSPathMap | null | undefined}
             */
            this["defaultWorkingDir"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * settings window X position, nil = unset (center on open)
             * @member
             * @type {number | null | undefined}
             */
            this["windowX"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * settings window Y position
             * @member
             * @type {number | null | undefined}
             */
            this["windowY"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * settings window width, min 480
             * @member
             * @type {number | null | undefined}
             */
            this["windowWidth"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * settings window height, min 400
             * @member
             * @type {number | null | undefined}
             */
            this["windowHeight"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * Category represents a group of related commands
 */
export class Category {
    /**
     * Creates a new Category instance.
     * @param {Partial<Category>} [$$source = {}] - The source object to create the Category.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Category instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Category}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Category(/** @type {Partial<Category>} */($$parsedSource));
    }
}

/**
 * Command represents a saved CLI command
 */
export class Command {
    /**
     * Creates a new Command instance.
     * @param {Partial<Command>} [$$source = {}] - The source object to create the Command.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {sql$0.NullString}
             */
            this["title"] = (new sql$0.NullString());
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {sql$0.NullString}
             */
            this["description"] = (new sql$0.NullString());
        }
        if (!("scriptContent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scriptContent"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("variables" in $$source)) {
            /**
             * @member
             * @type {VariableDefinition[]}
             */
            this["variables"] = [];
        }
        if (!("presets" in $$source)) {
            /**
             * @member
             * @type {VariablePreset[]}
             */
            this["presets"] = [];
        }
        if (!("workingDir" in $$source)) {
            /**
             * @member
             * @type {OSPathMap}
             */
            this["workingDir"] = null;
        }
        if (!("categoryId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["categoryId"] = "";
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["position"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Command instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Command}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("title" in $$parsedSource) {
            $$parsedSource["title"] = $$createField1_0($$parsedSource["title"]);
        }
        if ("description" in $$parsedSource) {
            $$parsedSource["description"] = $$createField2_0($$parsedSource["description"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField5_0($$parsedSource["variables"]);
        }
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField6_0($$parsedSource["presets"]);
        }
        return new Command(/** @type {Partial<Command>} */($$parsedSource));
    }
}

/**
 * EventNames holds all Wails event name constants, exposed to frontend via GetEventNames().
 */
export class EventNames {
    /**
     * Creates a new EventNames instance.
     * @param {Partial<EventNames>} [$$source = {}] - The source object to create the EventNames.
     */
    constructor($$source = {}) {
        if (!("openSettings" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["openSettings"] = "";
        }
        if (!("openShortcuts" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["openShortcuts"] = "";
        }
        if (!("settingsChanged" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["settingsChanged"] = "";
        }
        if (!("settingsWindowClosing" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["settingsWindowClosing"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventNames instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EventNames}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EventNames(/** @type {Partial<EventNames>} */($$parsedSource));
    }
}

/**
 * ExecutionRecord captures a single command execution for history
 */
export class ExecutionRecord {
    /**
     * Creates a new ExecutionRecord instance.
     * @param {Partial<ExecutionRecord>} [$$source = {}] - The source object to create the ExecutionRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("commandId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandId"] = "";
        }
        if (!("scriptContent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scriptContent"] = "";
        }
        if (!("finalCmd" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["finalCmd"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("exitCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["exitCode"] = 0;
        }
        if (!("workingDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workingDir"] = "";
        }
        if (!("executedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["executedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecutionRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExecutionRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecutionRecord(/** @type {Partial<ExecutionRecord>} */($$parsedSource));
    }
}

/**
 * OSPathMap stores OS-keyed file paths as a JSON object
 * @typedef {any} OSPathMap
 */

/**
 * SessionInfo is the public metadata for a terminal session, sent to the frontend.
 */
export class SessionInfo {
    /**
     * Creates a new SessionInfo instance.
     * @param {Partial<SessionInfo>} [$$source = {}] - The source object to create the SessionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("shellPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shellPath"] = "";
        }
        if (!("workingDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workingDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo(/** @type {Partial<SessionInfo>} */($$parsedSource));
    }
}

/**
 * TerminalInfo describes a detected terminal emulator
 */
export class TerminalInfo {
    /**
     * Creates a new TerminalInfo instance.
     * @param {Partial<TerminalInfo>} [$$source = {}] - The source object to create the TerminalInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalInfo(/** @type {Partial<TerminalInfo>} */($$parsedSource));
    }
}

/**
 * VariableDefinition stores per-command variable metadata
 */
export class VariableDefinition {
    /**
     * Creates a new VariableDefinition instance.
     * @param {Partial<VariableDefinition>} [$$source = {}] - The source object to create the VariableDefinition.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("example" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["example"] = "";
        }
        if (!("default" in $$source)) {
            /**
             * plain value or CEL expression
             * @member
             * @type {string}
             */
            this["default"] = "";
        }
        if (!("sortOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VariableDefinition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VariableDefinition}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VariableDefinition(/** @type {Partial<VariableDefinition>} */($$parsedSource));
    }
}

/**
 * VariablePreset stores a named set of variable values for a command
 */
export class VariablePreset {
    /**
     * Creates a new VariablePreset instance.
     * @param {Partial<VariablePreset>} [$$source = {}] - The source object to create the VariablePreset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["position"] = 0;
        }
        if (!("values" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["values"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VariablePreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VariablePreset}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField3_0($$parsedSource["values"]);
        }
        return new VariablePreset(/** @type {Partial<VariablePreset>} */($$parsedSource));
    }
}

/**
 * VariablePrompt is returned to the frontend when prompting for variable values
 */
export class VariablePrompt {
    /**
     * Creates a new VariablePrompt instance.
     * @param {Partial<VariablePrompt>} [$$source = {}] - The source object to create the VariablePrompt.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("placeholder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["placeholder"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("example" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["example"] = "";
        }
        if (!("defaultExpr" in $$source)) {
            /**
             * raw CEL/literal expression from definition
             * @member
             * @type {string}
             */
            this["defaultExpr"] = "";
        }
        if (!("defaultValue" in $$source)) {
            /**
             * evaluated default ready to use
             * @member
             * @type {string}
             */
            this["defaultValue"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VariablePrompt instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VariablePrompt}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VariablePrompt(/** @type {Partial<VariablePrompt>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = sql$0.NullString.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = VariableDefinition.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = VariablePreset.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
