// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService handles user preferences and settings window.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSettings returns the current app settings.
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function GetSettings() {
    return $Call.ByID(3034808949).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetSettings updates the app settings from a JSON string.
 * @param {string} jsonStr
 * @returns {$CancellablePromise<void>}
 */
export function SetSettings(jsonStr) {
    return $Call.ByID(287946425, jsonStr);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
