// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService manages multiple PTY-backed shell sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Clear sends the ANSI clear sequence and emits a namespaced clear event.
 * @param {string} sessionId
 * @returns {$CancellablePromise<void>}
 */
export function Clear(sessionId) {
    return $Call.ByID(493646090, sessionId);
}

/**
 * CloseSession removes a session from the manager. If the closed session was the
 * active one, another session is assigned as active (or cleared if none remain).
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function CloseSession(id) {
    return $Call.ByID(3305403653, id);
}

/**
 * CreateSession creates a new terminal session with a UUID v4 ID and default name "Terminal N".
 * @returns {$CancellablePromise<$models.SessionInfo | null>}
 */
export function CreateSession() {
    return $Call.ByID(2914743863).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetActiveSession returns the SessionInfo for the currently active session,
 * or nil if no active session exists.
 * @returns {$CancellablePromise<$models.SessionInfo | null>}
 */
export function GetActiveSession() {
    return $Call.ByID(1716291155).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListSessions returns SessionInfo for all sessions in the manager.
 * @returns {$CancellablePromise<($models.SessionInfo | null)[]>}
 */
export function ListSessions() {
    return $Call.ByID(1878753896).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RenameSession updates the name of a session. Returns an error if name is empty
 * or the session does not exist.
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenameSession(id, name) {
    return $Call.ByID(911254629, id, name);
}

/**
 * Resize changes the terminal dimensions for the specified session.
 * @param {string} sessionId
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Resize(sessionId, cols, rows) {
    return $Call.ByID(270758441, sessionId, cols, rows);
}

/**
 * SetActiveSession sets the active session by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveSession(id) {
    return $Call.ByID(4186280199, id);
}

/**
 * Start starts the PTY shell for the specified session.
 * @param {string} sessionId
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Start(sessionId, cols, rows) {
    return $Call.ByID(3774501399, sessionId, cols, rows);
}

/**
 * Stop stops the PTY shell for the specified session.
 * @param {string} sessionId
 * @returns {$CancellablePromise<void>}
 */
export function Stop(sessionId) {
    return $Call.ByID(2555571709, sessionId);
}

/**
 * Write sends input data to the specified session's PTY.
 * @param {string} sessionId
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function Write(sessionId, data) {
    return $Call.ByID(371925220, sessionId, data);
}

// Private type creation functions
const $$createType0 = $models.SessionInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
