// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TerminalService manages multiple PTY-backed shell sessions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Clear makes the shell clear its own screen, the same way it would if the
 * user pressed Ctrl+L (or typed cls/clear and Enter) themselves — see
 * clearKeyFor. This is why letting the shell do it (rather than writing an
 * ANSI clear sequence straight into ss.ptmx, which a previous version did)
 * matters: PSReadLine (and bash/zsh's own line editor) track the real
 * console's cursor position via absolute Win32/terminfo addressing, which a
 * purely client-side xterm.js clear can never see. If only the frontend's
 * buffer is wiped, the shell's next prompt redraw still targets whatever
 * absolute row it last believed the cursor was at, and xterm.js — now
 * otherwise empty — pads up to that row with blank lines to honor the
 * positioning request, which is exactly the "empty line from before"
 * glitch this fixes. Driving the shell's own clear keeps its internal
 * cursor tracking and the frontend's rendered buffer in sync, since both
 * are driven by the same clear-and-redraw the shell performs. The
 * pty-cleared event still fires for an immediate, optimistic frontend wipe;
 * the shell's own (slightly delayed) redraw arriving over the normal
 * output stream is what keeps the two in sync afterward.
 * @param {string} sessionId
 * @returns {$CancellablePromise<void>}
 */
export function Clear(sessionId) {
    return $Call.ByID(493646090, sessionId);
}

/**
 * CloseSession removes a session from the manager. If the closed session was the
 * active one, another session is assigned as active (or cleared if none remain).
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function CloseSession(id) {
    return $Call.ByID(3305403653, id);
}

/**
 * CreateInternalSession creates a session owned by app chrome rather than by
 * the user's terminal tabs. It is hidden from ListSessions and never becomes
 * the active session.
 * @param {string} name
 * @returns {$CancellablePromise<$models.SessionInfo | null>}
 */
export function CreateInternalSession(name) {
    return $Call.ByID(98262348, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateSession creates a new terminal session with a UUID v4 ID and default name "Terminal N".
 * @returns {$CancellablePromise<$models.SessionInfo | null>}
 */
export function CreateSession() {
    return $Call.ByID(2914743863).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetActiveSession returns the SessionInfo for the currently active session,
 * or nil if no active session exists.
 * @returns {$CancellablePromise<$models.SessionInfo | null>}
 */
export function GetActiveSession() {
    return $Call.ByID(1716291155).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetLastOutput returns the captured output of the most recently completed
 * command in the given session, as recorded via OSC 133 shell-integration
 * markers.
 * @param {string} sessionId
 * @returns {$CancellablePromise<$models.TerminalLastOutput>}
 */
export function GetLastOutput(sessionId) {
    return $Call.ByID(4011093730, sessionId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListSessions returns SessionInfo for all sessions in the manager.
 * @returns {$CancellablePromise<($models.SessionInfo | null)[]>}
 */
export function ListSessions() {
    return $Call.ByID(1878753896).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RenameSession updates the name of a session. Returns an error if name is empty
 * or the session does not exist.
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenameSession(id, name) {
    return $Call.ByID(911254629, id, name);
}

/**
 * Resize changes the terminal dimensions for the specified session.
 * @param {string} sessionId
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Resize(sessionId, cols, rows) {
    return $Call.ByID(270758441, sessionId, cols, rows);
}

/**
 * SetActiveSession sets the active session by ID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveSession(id) {
    return $Call.ByID(4186280199, id);
}

/**
 * Start starts the PTY shell for the specified session.
 * @param {string} sessionId
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Start(sessionId, cols, rows) {
    return $Call.ByID(3774501399, sessionId, cols, rows);
}

/**
 * Stop stops the PTY shell for the specified session.
 * @param {string} sessionId
 * @returns {$CancellablePromise<void>}
 */
export function Stop(sessionId) {
    return $Call.ByID(2555571709, sessionId);
}

/**
 * Write sends input data to the specified session's PTY. Session IDs are
 * intentionally addressable regardless of the internal flag: internal status
 * controls UI visibility/lifecycle only, not access control.
 * @param {string} sessionId
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function Write(sessionId, data) {
    return $Call.ByID(371925220, sessionId, data);
}

// Private type creation functions
const $$createType0 = $models.SessionInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.TerminalLastOutput.createFrom;
const $$createType3 = $Create.Array($$createType1);
