// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes the in-app updater to the frontend and runs the
 * opt-in periodic background check.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdates kicks off a headless check (+ auto-download when a release
 * is found). It returns immediately; the About dialog renders progress from
 * the wails:updater:* events. Dev builds get an error instead of silent
 * nothing.
 * @returns {$CancellablePromise<void>}
 */
export function CheckForUpdates() {
    return $Call.ByID(670986527);
}

/**
 * GetAppInfo returns the About snapshot. Dev builds report updatesEnabled
 * false with the unconfigured state; the dialog shows its dev-build copy.
 * @returns {$CancellablePromise<$models.AppInfo>}
 */
export function GetAppInfo() {
    return $Call.ByID(295420683).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetAppVersion returns the build-time version, or "dev" for local builds.
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(1469023009);
}

/**
 * GetSkippedVersion returns the version the user dismissed via
 * "Skip This Version", or "" if none.
 * @returns {$CancellablePromise<string>}
 */
export function GetSkippedVersion() {
    return $Call.ByID(1306757372);
}

/**
 * GetUpdateState returns the updater lifecycle state
 * (unconfigured/idle/checking/up-to-date/available/downloading/verifying/
 * installing/ready/error), or "unconfigured" for dev builds.
 * @returns {$CancellablePromise<string>}
 */
export function GetUpdateState() {
    return $Call.ByID(4160282334);
}

/**
 * RestartToUpdate restarts into the staged update after DownloadAndInstall
 * reports ready. Returns an error when nothing is staged (ErrNotReady).
 * @returns {$CancellablePromise<void>}
 */
export function RestartToUpdate() {
    return $Call.ByID(861895759);
}

/**
 * SetBetaChannel persists the prerelease toggle and rebuilds the provider so
 * the next check walks /releases (beta on) or /releases/latest (beta off).
 * It takes effect immediately, including for the running auto-check loop.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetBetaChannel(enabled) {
    return $Call.ByID(947562229, enabled);
}

/**
 * UpdatesEnabled reports whether the updater was configured. It is false for
 * local dev builds, where the update UI must stay hidden/disabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function UpdatesEnabled() {
    return $Call.ByID(2359163331);
}

// Private type creation functions
const $$createType0 = $models.AppInfo.createFrom;
