// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService exposes the in-app updater to the frontend and runs the
 * opt-in periodic background check.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CheckForUpdates opens the update window and runs check + download/install.
 * It returns immediately; the window itself reflects progress, errors, and
 * the up-to-date state. Dev builds get an error instead of silent nothing.
 * @returns {$CancellablePromise<void>}
 */
export function CheckForUpdates() {
    return $Call.ByID(670986527);
}

/**
 * GetAppVersion returns the build-time version, or "dev" for local builds.
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(1469023009);
}

/**
 * GetSkippedVersion returns the version the user dismissed via
 * "Skip This Version", or "" if none.
 * @returns {$CancellablePromise<string>}
 */
export function GetSkippedVersion() {
    return $Call.ByID(1306757372);
}

/**
 * GetUpdateState returns the updater lifecycle state
 * (unconfigured/idle/checking/up-to-date/available/downloading/verifying/
 * installing/ready/error), or "unconfigured" for dev builds.
 * @returns {$CancellablePromise<string>}
 */
export function GetUpdateState() {
    return $Call.ByID(4160282334);
}

/**
 * UpdatesEnabled reports whether the updater was configured. It is false for
 * local dev builds, where the update UI must stay hidden/disabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function UpdatesEnabled() {
    return $Call.ByID(2359163331);
}
